[theme]
base                  = "light"
primaryColor          = "#0FB6C2"
backgroundColor       = "#F5F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor             = "#0C1A2B"
font                  = "sans serif"

[server]
headless = true
